# Generated by Django 4.2.1 on 2023-07-11 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SendRequest_to_login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="Surename")),
                ("phone_number", models.IntegerField(verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(
                        default="example@gmail.com",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "scanned_document",
                    models.ImageField(
                        upload_to="images_of_sc_document",
                        verbose_name="Scanned Document",
                    ),
                ),
                (
                    "activate_profile",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default=0,
                        verbose_name="Activate Profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Allergist/Immunologist", "Allergist/Immunologist"),
                            ("Anesthesiologist", "Anesthesiologist"),
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologist", "Dermatologist"),
                            (
                                "Emergency Medicine Specialist",
                                "Emergency Medicine Specialist",
                            ),
                            ("Endocrinologist", "Endocrinologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("Geriatrician", "Geriatrician"),
                            ("Hematologist/Oncologist", "Hematologist/Oncologist"),
                            (
                                "Infectious Disease Specialist",
                                "Infectious Disease Specialist",
                            ),
                            (
                                "Internal Medicine Physician",
                                "Internal Medicine Physician",
                            ),
                            ("Nephrologist", "Nephrologist"),
                            ("Neurologist", "Neurologist"),
                            (
                                "Obstetrician/Gynecologist (OB/GYN)",
                                "Obstetrician/Gynecologist (OB/GYN)",
                            ),
                            ("Ophthalmologist", "Ophthalmologist"),
                            (
                                "Orthopedic Surgeon/Specialist",
                                "Orthopedic Surgeon/Specialist",
                            ),
                            (
                                "Otolaryngologist (ENT Specialist)",
                                "Otolaryngologist (ENT Specialist)",
                            ),
                            ("Pediatrician", "Pediatrician"),
                            (
                                "Physical Medicine and Rehabilitation Specialist",
                                "Physical Medicine and Rehabilitation Specialist",
                            ),
                            ("Psychiatrist", "Psychiatrist"),
                            (
                                "Pulmonologist (lung specialist)",
                                "Pulmonologist (lung specialist)",
                            ),
                            ("Radiologist", "Radiologist"),
                            ("Rheumatologist", "Rheumatologist"),
                        ],
                        max_length=120,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "sub_specializations",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        max_length=120,
                        verbose_name=[
                            ("Allergist/Immunologist", "Allergist/Immunologist"),
                            ("Anesthesiologist", "Anesthesiologist"),
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologist", "Dermatologist"),
                            (
                                "Emergency Medicine Specialist",
                                "Emergency Medicine Specialist",
                            ),
                            ("Endocrinologist", "Endocrinologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("Geriatrician", "Geriatrician"),
                            ("Hematologist/Oncologist", "Hematologist/Oncologist"),
                            (
                                "Infectious Disease Specialist",
                                "Infectious Disease Specialist",
                            ),
                            (
                                "Internal Medicine Physician",
                                "Internal Medicine Physician",
                            ),
                            ("Nephrologist", "Nephrologist"),
                            ("Neurologist", "Neurologist"),
                            (
                                "Obstetrician/Gynecologist (OB/GYN)",
                                "Obstetrician/Gynecologist (OB/GYN)",
                            ),
                            ("Ophthalmologist", "Ophthalmologist"),
                            (
                                "Orthopedic Surgeon/Specialist",
                                "Orthopedic Surgeon/Specialist",
                            ),
                            (
                                "Otolaryngologist (ENT Specialist)",
                                "Otolaryngologist (ENT Specialist)",
                            ),
                            ("Pediatrician", "Pediatrician"),
                            (
                                "Physical Medicine and Rehabilitation Specialist",
                                "Physical Medicine and Rehabilitation Specialist",
                            ),
                            ("Psychiatrist", "Psychiatrist"),
                            (
                                "Pulmonologist (lung specialist)",
                                "Pulmonologist (lung specialist)",
                            ),
                            ("Radiologist", "Radiologist"),
                            ("Rheumatologist", "Rheumatologist"),
                        ],
                    ),
                ),
                (
                    "working_schedule",
                    models.JSONField(default=dict, verbose_name="Working Schedule"),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
