# Generated by Django 4.2.2 on 2023-07-04 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor_user_Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.IntegerField(verbose_name="Password")),
                ("phone_number", models.IntegerField(verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "scanned_document",
                    models.ImageField(
                        upload_to="images_of_sc_document",
                        verbose_name="Scanned Document",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=50, verbose_name="Specialization"),
                ),
                ("working_time", models.TimeField(verbose_name="Working Time")),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
