# Generated by Django 4.2.2 on 2023-07-04 14:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor_user_registration",
            name="working_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("item_key1", "Item title 1.1"),
                    ("item_key2", "Item title 1.2"),
                    ("item_key3", "Item title 1.3"),
                    ("item_key4", "Item title 1.4"),
                    ("item_key5", "Item title 1.5"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
