# Generated by Django 4.2.2 on 2023-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor_user_registration",
            name="working_time",
            field=models.JSONField(default={}, verbose_name="Working Time"),
        ),
    ]
