# Generated by Django 4.2.2 on 2023-07-04 14:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0002_doctor_user_registration_working_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_user_registration",
            name="working_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
