# Generated by Django 4.2.1 on 2023-07-11 11:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0003_doctor_profile_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_profile",
            name="sub_specializations",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Allergist/Immunologist", "Allergist/Immunologist"),
                    ("Anesthesiologist", "Anesthesiologist"),
                    ("Cardiologist", "Cardiologist"),
                    ("Dermatologist", "Dermatologist"),
                    ("Emergency Medicine Specialist", "Emergency Medicine Specialist"),
                    ("Endocrinologist", "Endocrinologist"),
                    ("Gastroenterologist", "Gastroenterologist"),
                    ("Geriatrician", "Geriatrician"),
                    ("Hematologist/Oncologist", "Hematologist/Oncologist"),
                    ("Infectious Disease Specialist", "Infectious Disease Specialist"),
                    ("Internal Medicine Physician", "Internal Medicine Physician"),
                    ("Nephrologist", "Nephrologist"),
                    ("Neurologist", "Neurologist"),
                    (
                        "Obstetrician/Gynecologist (OB/GYN)",
                        "Obstetrician/Gynecologist (OB/GYN)",
                    ),
                    ("Ophthalmologist", "Ophthalmologist"),
                    ("Orthopedic Surgeon/Specialist", "Orthopedic Surgeon/Specialist"),
                    (
                        "Otolaryngologist (ENT Specialist)",
                        "Otolaryngologist (ENT Specialist)",
                    ),
                    ("Pediatrician", "Pediatrician"),
                    (
                        "Physical Medicine and Rehabilitation Specialist",
                        "Physical Medicine and Rehabilitation Specialist",
                    ),
                    ("Psychiatrist", "Psychiatrist"),
                    (
                        "Pulmonologist (lung specialist)",
                        "Pulmonologist (lung specialist)",
                    ),
                    ("Radiologist", "Radiologist"),
                    ("Rheumatologist", "Rheumatologist"),
                ],
                max_length=120,
            ),
        ),
    ]
