# Generated by Django 4.2.1 on 2023-07-11 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0004_alter_doctor_profile_sub_specializations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_profile",
            name="working_schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=30), size=10
                ),
                size=10,
            ),
        ),
    ]
