# Generated by Django 4.2.1 on 2023-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0005_alter_doctor_profile_working_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor_profile",
            name="working_schedule",
        ),
    ]
