# Generated by Django 4.2.2 on 2023-07-06 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0005_alter_doctor_user_registration_working_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor_user_registration",
            name="working_days",
        ),
    ]
