# Generated by Django 4.2.2 on 2023-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0006_remove_doctor_user_registration_working_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor_user_registration",
            name="working_time",
        ),
        migrations.AddField(
            model_name="doctor_user_registration",
            name="working_schedule",
            field=models.JSONField(default=dict, verbose_name="Working Schedule"),
        ),
    ]
