# Generated by Django 4.2.1 on 2023-07-12 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0007_doctor_profile_working_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_profile",
            name="working_schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=100),
                    default=list,
                    size=10,
                ),
                default=list,
                size=10,
            ),
        ),
    ]
