# Generated by Django 4.2.2 on 2023-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0007_alter_sendrequest_to_login_activate_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendrequest_to_login",
            name="activate_profile",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default=0,
                verbose_name="Activate Profile",
            ),
        ),
    ]
