# Generated by Django 4.2.1 on 2023-07-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0007_remove_doctor_user_registration_working_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendrequest_to_login",
            name="email",
            field=models.EmailField(
                default="example@gmail.com",
                max_length=254,
                verbose_name="Email Address",
            ),
        ),
    ]
