# Generated by Django 4.2.2 on 2023-07-05 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor_panel", "0008_alter_sendrequest_to_login_activate_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_user_registration",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
