# Generated by Django 4.2.1 on 2023-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_panel", "0008_alter_doctor_profile_working_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor_profile",
            name="additional_description",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="doctor_profile",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctor_profile",
            name="study_description",
            field=models.CharField(default=".", max_length=1000),
        ),
    ]
